# Generated by Django 4.2.6 on 2023-11-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodata',
            name='search',
            field=models.CharField(default='', max_length=255),
        ),
    ]
