# Generated by Django 4.2.6 on 2023-11-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('card_expiry_month', models.CharField(max_length=2)),
                ('card_expiry_year', models.CharField(max_length=4)),
                ('card_cvc', models.CharField(max_length=3)),
            ],
        ),
    ]
