# Generated by Django 4.2.5 on 2023-11-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internetProject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="complaint_attachments/"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=15)),
            ],
        ),
    ]
