# Generated by Django 4.2.6 on 2023-11-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internetProject', '0002_cryptodata_search'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cryptodata',
            unique_together={('limit', 'offset', 'search')},
        ),
    ]
