# Generated by Django 4.2.7 on 2023-11-24 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internetProject', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id_proof',
            new_name='id_proof_path',
        ),
    ]
