# Generated by Django 4.2.6 on 2023-11-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internetProject', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
