# Generated by Django 4.2.6 on 2023-11-27 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internetProject', '0007_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('icon_url', models.URLField()),
                ('tier', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('price', models.FloatField()),
                ('btc_price', models.FloatField()),
                ('price_at', models.DateTimeField()),
                ('number_of_markets', models.IntegerField()),
                ('number_of_exchanges', models.IntegerField()),
                ('volume_24h', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('fully_diluted_market_cap', models.FloatField()),
                ('change', models.FloatField()),
                ('all_time_high_price', models.FloatField()),
                ('all_time_high_timestamp', models.DateTimeField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('website_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CryptoStateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('type',)},
            },
        ),
        migrations.CreateModel(
            name='CryptoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('offset', models.IntegerField()),
                ('data', models.JSONField()),
                ('total_items', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('limit', 'offset')},
            },
        ),
    ]
