# Generated by Django 5.0a1 on 2023-11-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0002_currency_rate_remove_exchange_from_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_rate',
            name='rate',
            field=models.FloatField(),
        ),
    ]
